### ISSUE TITLE
cisco.meraki.networks_appliance_ports is failing with "Object does not exists, plugin only has update"

### ISSUE THREAD

**Issue by obrigg** [jbogarin/meraki-ansible-test#14]
`cisco.meraki.networks_appliance_ports` is failing too.

```
---

- hosts: meraki_servers
  vars:
    network_id: "L_828099381482770865"
  gather_facts: false
  tasks:

    - name: Update appliance ports
      cisco.meraki.networks_appliance_ports:
        accessPolicy: "open"
        allowedVlans: "all"
        enabled: true
        networkId: "{{network_id}}"
        portId: "2"
        type: "access"
        vlan: 3
        state: present
```

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [meraki_server]: FAILED! => {"changed": false, "msg": "Object does not exists, plugin only has update"}`
