### ISSUE TITLE
cisco.meraki.networks_appliance_traffic_shaping is failing with "Object does not exists, plugin only has update

### ISSUE THREAD

**Issue by obrigg** [jbogarin/meraki-ansible-test#19]
```
    - name: Update appliance traffic shaping
      cisco.meraki.networks_appliance_traffic_shaping:
        state: present
        globalBandwidthLimits:
          limitDown: 5120
          limitUp: 2048
        networkId: "{{network_id}}"
```
