### ISSUE TITLE
idempotency broken on networks_appliance_firewall_l3_firewall_rules

### ISSUE THREAD

**Issue by craigers521** [jbogarin/meraki-ansible-test#20]
#### Behavior

When running a play to configure L3 firewall rules the play notes a change being made everytime, even re-running the same play. 

#### Example playbook

```yaml
- name: Configure MX VLANs
  hosts: craig-home-mx1
  connection: local
  collections:
    - cisco.meraki
  tasks:

  - name: Configure L3 rules
    networks_appliance_firewall_l3_firewall_rules:
      meraki_api_key: "{{ meraki_api_key }}"
      meraki_suppress_logging: "{{meraki_suppress_logging}}"
      networkId: "{{ networkId }}"
      rules: "{{ l3_rules }}"
      state: present
    register: result
    when: "'appliances' in group_names"
```

#### Suspected Issue

when doing a GET of meraki L3 FW rules it always includes the default firewall rule, but if you attempt to do a POST that includes the default rule it attempts to add it as an additional custom rule.   If we can ignore 

#### Expected behavior

idempotency works and ansible does now show a change being made

#### environment 

MacOS Ventura 13.4
ansible-core==2.15.1
meraki==1.34.0
Python 3.11.4

ansible.utils 2.10.3
cisco.meraki 1.0.0

**Comment by obrigg** [comment]
I noticed that, and I think it's because of the default rule we have.

I configure this:
```
    - name: Create FW outbound L3 rules
      cisco.meraki.networks_appliance_firewall_l3_firewall_rules:
        networkId: "{{network_id}}"
        state: present
        rules:
          - comment: Block internetbadguys.com
            destCidr: internetbadguys.com
            destPort: any
            policy: deny
            protocol: any
            srcCidr: any
            syslogEnabled: false
```
But get this:
```
        "meraki_response": {
            "rules": [
                {
                    "comment": "Block internetbadguys.com",
                    "destCidr": "internetbadguys.com",
                    "destPort": "Any",
                    "policy": "deny",
                    "protocol": "any",
                    "srcCidr": "Any",
                    "srcPort": "Any",
                    "syslogEnabled": false
                },
                {
                    "comment": "Default rule",
                    "destCidr": "Any",
                    "destPort": "Any",
                    "policy": "allow",
                    "protocol": "Any",
                    "srcCidr": "Any",
                    "srcPort": "Any",
                    "syslogEnabled": false
                }
            ]
        },
```
