### ISSUE TITLE
devices_camera_quality_and_retention - problematic attribute

### ISSUE THREAD

**Issue by obrigg** [jbogarin/meraki-ansible-test#24]
Running the following task:
```
  - name: Update quality and retention settings
    cisco.meraki.devices_camera_quality_and_retention:
      serial: "{{ serial_number }}"
      audioRecordingEnabled: true
      motionBasedRetentionEnabled: true
      motionDetectorVersion: 2
      quality: High
      resolution: 1920x1080
      restrictedBandwidthModeEnabled: false
```   
I am getting an error about `audioRecordingEnabled` and `restrictedBandwidthModeEnabled` must be booleans, even though they are.
