### ISSUE TITLE
Updating switch_port is failing

### ISSUE THREAD

**Issue by obrigg** [jbogarin/meraki-ansible-test#8]
Trying to run this playbook:
```
---
- hosts: meraki_servers
  gather_facts: false
  tasks:
    - name: update ports
      cisco.meraki.devices_switch_ports:
        meraki_suppress_logging: true
        state: present
        serial: "QBSB-D5ZD-9CXT"
        vlan: 10
        portId: 1 
```

It's failing with the following error: `Object does not exists, plugin only has update`
